"""Restructuring for asynchronous database

Revision ID: 87d64e443e5f
Revises: 4c762a7dbb3e
Create Date: 2026-06-11 10:04:45.460321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d64e443e5f'
down_revision: Union[str, Sequence[str], None] = '4c762a7dbb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
