"""add index to username column in User & user_id column in Stat

Revision ID: f7cab4276071
Revises: 87d64e443e5f
Create Date: 2026-06-12 02:06:04.692269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cab4276071'
down_revision: Union[str, Sequence[str], None] = '87d64e443e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stats_user_id_key'), 'stats', type_='unique')
    op.create_index(op.f('ix_stats_user_id'), 'stats', ['user_id'], unique=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_stats_user_id'), table_name='stats')
    op.create_unique_constraint(op.f('stats_user_id_key'), 'stats', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
